### ISSUE TITLE
Need to install:broadcasting separately?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/collaboration#101]
Hi

I installed `php please install:collaboration`, set everything up

- I've added the Pusher credentials to my .env
- Enabled the "Client Events" setting in Pusher Dashboard
- BROADCAST_CONNECTION=pusher

I've ran `php artisan config:cache` , but I still see a `Attempting websocket connection... message`

- Running Statamic 5.8.0
- Collaboration 1.0.0

I see this error message in Pusher Dashboard
```
Cannot broadcast client event (connection not subscribed to channel presence-entry.xxxxxxx-xxx-xxxx
x-0a0b38903058.default)
```

Dev Tools in the /cp shows a missing file?
```
broadcasting/auth 404 (Not Found)
```

I asked about this in Discord
https://discord.com/channels/489818810157891584/1252923239307415653

I was advised to install broadcasting manually.
```
php artisan install:broadcasting
```

I did, and that fixed it.

However the docs indicate this is done as part of the `php please install:collaboration` command.

Is there something wrong with the addon, or do the docs need updating?

**Comment by duncanmcclean** [comment]
Statamic's `install:collaboration` should be running that command behind the scenes, without you needing to do anything ([see here for reference](https://github.com/statamic/cms/blob/5.x/src/Console/Commands/InstallCollaboration.php#L77)).

Which version of Laravel are you using?

**Comment by stephenmeehanuk** [comment]
I thought so too.

```
Laravel Version: 11.10.0
PHP Version: 8.3.8
```

**Comment by stephenmeehanuk** [comment]
Ah, when I ran `install:broadcasting` I said yes to the 'install node dependencies'. Looks like that's not required.

Line 77
```
'install:broadcasting',
                    '--without-reverb',
                    '--without-node',
```

**Comment by duncanmcclean** [comment]
Okay, there must be a bug in the command, I'll take a look. Thanks!
