### ISSUE TITLE
Broken bard field after live preview was opened

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/collaboration#16]
If several users work in the same entry, the bard field can be broken. Reproducible by:

1. user 1 blocks bard field and adds a set 
2. user 2 sees set collapsed (at this point, maybe not quite as bad as I thought)
![Bildschirmfoto 2019-11-07 um 09 39 50](https://user-images.githubusercontent.com/54707973/68373927-21852800-0144-11ea-95c1-30475c7ac7c9.png)
3. user 2 goes to live preview and closes the live preview again
4. user 2 will not see the sets in the bard field correctly anymore
![Bildschirmfoto 2019-11-07 um 09 42 56](https://user-images.githubusercontent.com/54707973/68374146-9ce6d980-0144-11ea-9659-ff8db46636e0.png)

**Comment by jasonvarga** [comment]
This fix requires some changes from the Statamic core (beta.10)

**Comment by WiebkeVog** [comment]
Could reproduce the behavior with the latest Core and Collboration changes in the way described above.

**Comment by jasonvarga** [comment]
Is that because pusher isn’t sending back everything due to the messages being too large? @sauerbraten was talking about that.

**Comment by WiebkeVog** [comment]
Yes, I think so.
