### ISSUE TITLE
Multiuser: Code Fieldtype isn't blocked

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/collaboration#17]
When a user edits a Code Fieldtype, it isn't blocked. Means a second user could access the same code block.

**Comment by sauerbraten** [comment]
That commit didn't fix it, we believe.

It still occurs on revision 3ecf44e8, which is the commit immediately after the fix.

**Comment by jasonvarga** [comment]
Did you compile and copy over the assets after checking out that commit?

**Comment by WiebkeVog** [comment]
Sorry our mistake. We wrapped the CodeFieldtype and forgot to add `@blur` and `@focus`. Now also works for us :)

**Comment by jasonvarga** [comment]
Cool :) Why did you need to wrap the code field?
