### ISSUE TITLE
Large Bard field values fail to synchronize

### ISSUE THREAD

**Issue by sauerbraten** [statamic/collaboration#21]
Pusher only supports payloads up to 10KB. Bard fields with a lot of content exceed this limit and changes made by one user are invisible to everyone else.

They suggest a few solutions here: https://support.pusher.com/hc/en-us/articles/360019115473

Another way forward could be to make use of tiptap's/prosemirror's support for collaboration where only the changes instead of the entire new field value is sent to peers, but this requires special casing Bard fields.

**Comment by sauerbraten** [comment]
The same issue could occur with large field values of any type of course. We have large Replicator fields for example, which when serialized to JSON might hit the same message size limit.

**Comment by jasonvarga** [comment]
Bummer. I think chunking will need to be the way to go.

**Comment by sauerbraten** [comment]
We sometimes see a first chunk that exceeds 11,000 bytes. This means the entire chunked message doesn't make it to other users. Maybe reduce the chunk size to something like 8,000 bytes to be safe?
