### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jackmcdade** [statamic/collaboration#40]
Getting this running again locally and the JS is throwing some errors.

```
Uncaught SyntaxError: Cannot use import statement outside a module
```

![image](https://user-images.githubusercontent.com/44739/118116894-ddb65300-b3b8-11eb-8cc0-6893a574d7d2.png)

Also, maybe related, the js/audio resources didn't auto-publish, and the vendor:publish script didn't work so I had to manually copy and paste the files into place. _maybe_ this stems from me not copying everything or something, or my symlinked sandbox?

**Comment by duncanmcclean** [comment]
The publishing issue is related to #25.

**Comment by jasonvarga** [comment]
Yeah you need to compile with mix.
