### ISSUE TITLE
Missing functionality

### ISSUE THREAD

**Issue by espenlg** [statamic/collaboration#45]
When we installed this addon and tried it out the first part with presence indicators works fine, but the rest is not happening:
 
* Fields get locked when someone else focuses them.
* Updates to field values are reflected to everyone.

Is there anything we need to do to enable / be aware of to make it work?

**Comment by espenlg** [comment]
And then I found the solution. Client events needs to be enabled in Pusher App Settings. Maybe add it to the get-started guide?

**Comment by espenlg** [comment]
Sorry about not reading that important line about Clients Events in the doc ;)

**Comment by jackmcdade** [comment]
No worries!
