### ISSUE TITLE
Statamic 3.4.0 Support

### ISSUE THREAD

**Issue by ben182** [statamic/collaboration#74]

**Comment by jackmcdade** [comment]
Done. Thanks for the reminder!

**Comment by tao** [comment]
@jackmcdade I'm having trouble updating because composer can't find the v5 `dist.tar.gz` file that the other releases have... is that something you still have to manually create or is GitHub supposed to add it automatically?

**Comment by tao** [comment]
```
In CurlDownloader.php line 623:
--
The "https://github.com/statamic/collaboration/releases/download/v0.5.0/dist.tar.gz" file could not be downloaded (HTTP/2 404 )
```

**Comment by duncanmcclean** [comment]
Ah, it'll need to be tagged in the command line, pushed up, then GitHub Actions will handle the actual release.

I think the latest release was tagged within GitHub.

cc @jackmcdade

**Comment by jackmcdade** [comment]
On it!

**Comment by jackmcdade** [comment]
There we go.
