### ISSUE TITLE
Fields doesnt update after another user change some text on random field

### ISSUE THREAD

**Issue by Pickle99** [statamic/collaboration#86]
So, i just downloaded this package, i can hear the sounds that another user joined the page which im filling, also i can see the user-s icon and etc at the top.

However when another user or me update some field on this page, i cant see the changes in field, still need to refresh the page to see the changes.

**Comment by jackmcdade** [comment]
Did you set up the Pusher account part?

**Comment by Pickle99** [comment]
Yes, just fixed it. I forgot to turn on the Client Events on pusher

**Comment by Pickle99** [comment]
This page is great btw. Thanks!

**Comment by jackmcdade** [comment]
Awesome! Glad you got it working!
